# Generated by Django 2.2.10 on 2020-04-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0002_serviceorder_per_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
    ]
