# Generated by Django 2.2.10 on 2020-04-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0003_auto_20200416_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='job',
        ),
    ]
