# Generated by Django 2.2.10 on 2020-04-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='per_merter',
            field=models.BooleanField(default=False),
        ),
    ]
