# Generated by Django 2.2.10 on 2020-04-16 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200415_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='per_merter',
            new_name='per_meter',
        ),
    ]
