# Generated by Django 2.2.10 on 2020-04-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200415_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='value_per_meter',
            field=models.FloatField(default=0),
        ),
    ]
