# Generated by Django 2.2.10 on 2020-04-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200415_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='value_per_meter',
            field=models.FloatField(null=True),
        ),
    ]
