# Generated by Django 2.2.10 on 2020-06-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200415_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('equipment_model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProtectiveEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('equipment_model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='has_ppe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobGroup'),
        ),
        migrations.AlterField(
            model_name='job',
            name='value_per_meter',
            field=models.FloatField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobEquipment'),
        ),
        migrations.AddField(
            model_name='job',
            name='ppe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.PersonalProtectiveEquipment'),
        ),
    ]
