version: '3'

services:

  mithrandir_db:
    image: mariadb:10.3
    restart: always
    container_name: mithrandir_MDB
    environment: 
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $ MYSQL_ROOT_PASSWORD

  mithrandir:
    build: .    
    image: mithrandir:devel
    restart: on-failure
    container_name: mithrandir_container
    command: gunicorn -w 3 mithrandir.wsgi:application -b :6006
    environment: 
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $ MYSQL_ROOT_PASSWORD
      SECRET_KEY: $SECRET_KEY
    volumes:
      - .:/app
      - static_data:/app/static
      - ".:/usr/src/code"
    expose:
      - "6006"
    depends_on:
      - mithrandir_db

volumes: 
  static_data:
